spring:
  application:
    name: orderline

server:
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOST}:${DISCOVERY_SERVICE_PORT}/eureka/        
    
logging:
  level:
    com.elipcero: INFO